BanDieuFood/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using BanDieuFood.Areas.HelpPage.ModelDescriptions;
using BanDieuFood.Areas.HelpPage.Models;

namespace BanDieuFood.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

BanDieuFood/Controllers/CartController.cs
using BanDieuFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanDieuFood.Controllers
{
    public class CartController : Controller
    {
        private readonly BanDieuDBContext _context;

        public CartController(BanDieuDBContext context)
        {
            _context = context;

        }
        // GET: Cart
        public List<CartItem> GioHang
        {
            get
            {
                List<CartItem> Cart = (List<CartItem>)Session["giohang"];
                if (Cart == default(List<CartItem>))
                {
                    Cart = new List<CartItem>();
                }
                return Cart;
            }
        }
        public ActionResult AddToCart(int productID, int? amount)
        {
            List<CartItem> cart = GioHang;

            try
            {
                //Them san pham vao gio hang
                CartItem item = cart.SingleOrDefault(p => p.product.ProductID == productID);
                if (item != null) // da co => cap nhat so luong
                {
                    item.amount = item.amount + amount.Value;
                    //luu lai session
                    List<CartItem> Cart1 = (List<CartItem>)Session["giohang"];
                }
                else
                {
                    Product hh = _context.Products.SingleOrDefault(p => p.ProductID == productID);
                    item = new CartItem
                    {
                        amount = amount.HasValue ? amount.Value : 1,
                        product = hh
                    };
                    cart.Add(item);
                }

                //Luu lai Session
                List<CartItem> Cart = (List<CartItem>)Session["giohang"];

                return Json(new { success = true });
            }
            catch
            {
                return Json(new { success = false });
            }
        }
        public ActionResult UpdateCart(int productID, int? amount)
        {
            //Lay gio hang ra de xu ly
            List<CartItem> Cart = (List<CartItem>)Session["giohang"];
            try
            {
                if (Cart != null)
                {
                    CartItem item = Cart.SingleOrDefault(p => p.product.ProductID == productID);
                    if (item != null && amount.HasValue) // da co -> cap nhat so luong
                    {
                        item.amount = amount.Value;
                    }
                    List<CartItem> Cart1 = (List<CartItem>)Session["giohang"];

                }
                return Json(new { success = true });
            }
            catch
            {
                return Json(new { success = false });
            }
        }
        public ActionResult Remove(int productID)
        {

            try
            {
                List<CartItem> gioHang = GioHang;
                CartItem item = gioHang.SingleOrDefault(p => p.product.ProductID == productID);
                if (item != null)
                {
                    gioHang.Remove(item);
                }
                //luu lai session
                List<CartItem> Cart = (List<CartItem>)Session["giohang"];
                return Json(new { success = true });
            }
            catch
            {
                return Json(new { success = false });
            }
        }

        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Checkout()
        {
            return View();
        }
    }
}

BanDieuFood/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanDieuFood.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SingleProduct()
        {
            return View();
        }
    }
}

BanDieuFood/Views/Shared/_Error404Custom.cshtml
@{
    ViewBag.Title = "_Error404Custom";
    Layout = "~/Views/Shared/_LayoutCustom.cshtml";
}
<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>Fresh adn Organic</p>
                    <h1>404 - Not Found</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->
<!-- error section -->
<div class="full-height-section error-section">
    <div class="full-height-tablecell">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="error-text">
                        <i class="far fa-sad-cry"></i>
                        <h1>Oops! Not Found.</h1>
                        <p>The page you requested for is not found.</p>
                        <a href="index.html" class="boxed-btn">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end error section -->

BanDieuFood/Views/Shared/_IntroductionPartial.cshtml
<div class="testimonail-section mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1 text-center">
                <div class="testimonial-sliders">
                    <div class="single-testimonial-slider">
                        <div class="client-avater">
                            <img src="~/AssetsClient/img/avaters/avtThien.jpg" alt="Anh loi">
                        </div>
                        <div class="client-meta">
                            <h3>Mr. Thiện<span>Sáng lập Bình Phước Food</span></h3>
                            <p class="testimonial-body">
                                "Uy tín tạo nên sự thành công"
                            </p>
                            <div class="last-icon">
                                <i class="fas fa-quote-right"></i>
                            </div>
                        </div>
                    </div>
                    <div class="single-testimonial-slider">
                        <div class="client-avater">
                            <img src="~/AssetsClient/img/avaters/Anhthe.jpg" alt="Anh loi">
                        </div>
                        <div class="client-meta">
                            <h3>Hieu Nghia <span>Cu li tại Bình Phước Food</span></h3>
                            <p class="testimonial-body">
                            </p>
                            <div class="last-icon">
                                @*<i class="fas fa-quote-right"></i>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

BanDieuFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Binh Phuoc Food</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Binh Phuoc Food</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BanDieuFood/Views/Shared/_LayoutCustom.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

    <!-- title -->
    <title>Binh Phuoc Food</title>
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="~/AssetsClient/img/favicon.png">
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <!-- fontawesome -->
    <link rel="stylesheet" href="~/AssetsClient/css/all.min.css">
    <!-- bootstrap -->
    <link rel="stylesheet" href="~/AssetsClient/bootstrap/css/bootstrap.min.css">
    <!-- owl carousel -->
    <link rel="stylesheet" href="~/AssetsClient/css/owl.carousel.css">
    <!-- magnific popup -->
    <link rel="stylesheet" href="~/AssetsClient/css/magnific-popup.css">
    <!-- animate css -->
    <link rel="stylesheet" href="~/AssetsClient/css/animate.css">
    <!-- mean menu css -->
    <link rel="stylesheet" href="~/AssetsClient/css/meanmenu.min.css">
    <!-- main style -->
    <link rel="stylesheet" href="~/AssetsClient/css/main.css">
    <!-- responsive -->
    <link rel="stylesheet" href="~/AssetsClient/css/responsive.css">

</head>
<body>

    <!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
    <!-- header -->
    <div class="top-header-area" id="sticker">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12 text-center">
                    <div class="main-menu-wrap">
                        <!-- logo -->
                        <div class="site-logo">
                            <a href=@Url.Action("Index", "Home")>
                                <img src="~/AssetsClient/img/logo-hatdieu.png" alt="Error image">
                            </a>
                        </div>
                        <!-- logo -->
                        <!-- menu start -->
                        <nav class="main-menu">
                            <ul>
                                <li class="current-list-item">
                                    <a href=@Url.Action("Index", "Home")>Trang chủ</a>
                                </li>
                                <li><a href=@Url.Action("About", "Home")>Giới thiệu</a></li>
                                <li>
                                    <a href="#">Pages</a>
                                    <ul class="sub-menu">
                                        <li><a href=@Url.Action("About", "Home")>Giới thiệu</a></li>
                                        <li><a href=@Url.Action("Index", "Cart")>Giỏ hàng</a></li>
                                        <li><a href=@Url.Action("Checkout", "Cart")>Check Out</a></li>
                                        <li><a href=@Url.Action("Contact", "Home")>Liên hệ</a></li>
                                        <li><a href=@Url.Action("News", "Home")>Tin tức về sản phẩm</a></li>
                                        <li><a href=@Url.Action("Index", "Product")</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Tin tức</a>
                                    <ul class="sub-menu">
                                        <li><a href=@Url.Action("News", "Home")>Tin tức về sản phẩm</a></li>
                                        <li><a href=@Url.Action("SingleNews", "Home")>Chi tiết</a></li>
                                    </ul>
                                </li>
                                <li><a href=@Url.Action("Contact", "Home")>Liên hệ</a></li>
                                <li>
                                    <a href=@Url.Action("Index", "Product")>Sản phẩm</a>
                                    <ul class="sub-menu">
                                        <li><a href=@Url.Action("Index", "Product")>Sản phẩm</a></li>
                                        <li><a href=@Url.Action("Checkout", "Cart")>Kiểm tra</a></li>
                                        <li><a href=@Url.Action("SingleNews", "Home")>Chi tiết sản phẩm</a></li>
                                        <li><a href=@Url.Action("Index", "Cart")>Giỏ hàng</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <div class="header-icons">
                                        <a class="shopping-cart" href=@Url.Action("Index", "Cart")><i class="fas fa-shopping-cart"></i></a>
                                        <a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
                                    </div>
                                </li>
                            </ul>
                        </nav>
                        <a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
                        <div class="mobile-menu"></div>
                        <!-- menu end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end header -->
    <!-- search area -->
    <div class="search-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <span class="close-btn"><i class="fas fa-window-close"></i></span>
                    <div class="search-bar">
                        <div class="search-bar-tablecell">
                            <h3>Tìm kiếm:</h3>
                            <input type="text" placeholder="Keywords">
                            <button type="submit">Tìm kiếm <i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end search area -->
    @RenderBody()
    <!-- logo carousel -->
    <div class="logo-carousel-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="logo-carousel-inner">
                        <div class="single-logo-item">
                            <img src="~/AssetsClient/img/company-logos/1.png" alt="">
                        </div>
                        <div class="single-logo-item">
                            <img src="~/AssetsClient/img/company-logos/2.png" alt="">
                        </div>
                        <div class="single-logo-item">
                            <img src="~/AssetsClient/img/company-logos/3.png" alt="">
                        </div>
                        <div class="single-logo-item">
                            <img src="~/AssetsClient/img/company-logos/4.png" alt="">
                        </div>
                        <div class="single-logo-item">
                            <img src="~/AssetsClient/img/company-logos/5.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end logo carousel -->
    <!-- footer -->
    <div class="footer-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-box about-widget">
                        <h2 class="widget-title">Giới thiệu</h2>
                        <p>Bình phước Food</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-box get-in-touch">
                        <h2 class="widget-title">Địa điểm</h2>
                        <ul>
                            <li>Bình phước, Việt Nam</li>
                            <li>binhphuocfood@gmail.com</li>
                            <li>+84399864429</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-box pages">
                        <h2 class="widget-title">Trang</h2>
                        <ul>
                            <li><a href=@Url.Action("Index", "Home")>Trang chủ</a></li>
                            <li><a href=@Url.Action("About", "Home")>Giới thiệu</a></li>
                            <li><a href=@Url.Action("Index", "Product")>Sản phẩm</a></li>
                            <li><a href=@Url.Action("News", "Home")>Tin tức</a></li>
                            <li><a href="contact.html">Liên hệ</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-box subscribe">
                        <h2 class="widget-title">Đăng ký theo dỗi</h2>
                        <p>Đăng ký để nhận thông tin mới nhất từ trang web.</p>
                        <form action="index.html">
                            <input type="email" placeholder="Email">
                            <button type="submit"><i class="fas fa-paper-plane"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end footer -->
    <!-- copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <p>
                        Bản quyền &copy; 2023 - <a href="https://imransdesign.com/">Binh Phuoc Food</a>,  All Rights Reserved.<br>
                        
                    </p>
                </div>
                <div class="col-lg-6 text-right col-md-12">
                    <div class="social-icons">
                        <ul>
                            <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
                            <li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end copyright -->
    <!-- jquery -->

    <script src="~/AssetsClient/js/jquery-1.11.3.min.js"></script>
    <!-- bootstrap -->
    <script src="~/AssetsClient/bootstrap/js/bootstrap.min.js"></script>
    <!-- count down -->
    <script src="~/AssetsClient/js/jquery.countdown.js"></script>
    <!-- isotope -->
    <script src="~/AssetsClient/js/jquery.isotope-3.0.6.min.js"></script>
    <!-- waypoints -->
    <script src="~/AssetsClient/js/waypoints.js"></script>
    <!-- owl carousel -->
    <script src="~/AssetsClient/js/owl.carousel.min.js"></script>
    <!-- magnific popup -->
    <script src="~/AssetsClient/js/jquery.magnific-popup.min.js"></script>
    <!-- mean menu -->
    <script src="~/AssetsClient/js/jquery.meanmenu.min.js"></script>
    <!-- sticker js -->
    <script src="~/AssetsClient/js/sticker.js"></script>
    <!-- main js -->
    <script src="~/AssetsClient/js/main.js"></script>
</body>
</html>